version: "3"
services: 
    db:
        restart: always
        image: postgres
        container_name: postgres
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: TBQForms
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        ports: 
            - '5432:5432'

    api: 
        build: 
            context: ./TBQForms_server/
            dockerfile: Dockerfile
        image: tbqforms_server
        container_name: tbqforms_server
        depends_on: 
            - db
        restart: always
        env_file: ./TBQForms_server/.env
        ports: 
            - '3000:3000'
        volumes: 
            - .:/home/node/TBQforms_server
            - ./node_modules:/home/node/TBQforms_server/node_modules

    proxy:
        image: nginx
        container_name: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/ssl:/etc/nginx/ssl
            - ./TBQForms_client/build:/home/client/build
        ports: 
            - '443:443'
            - '80:80'
        depends_on: 
            - api
        restart: always